server:
  port: 8080

spring:
  application:
    name: fraud-detection-system

  kafka:
    # 'localhost:9092' connects from your Ubuntu host to the Docker broker
    # 'broker:29092' would be used if the App itself was in Docker
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        request.timeout.ms: 2000
        delivery.timeout.ms: 3000
        retries: 0

    streams:
      application-id: ${spring.application.name}-streams
      properties:
        # Essential for exactly_once_v2 to work with your single-node broker
        processing.guarantee: exactly_once_v2
        auto.offset.reset: earliest
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        # Ensure this matches your package structure
        spring.json.value.default.type: com.raaz.fraud_detection_system.domain.Transaction

  jackson:
    serialization:
      write-dates-as-timestamps: false

# Senior Tip: Customizing the paths and ensuring Swagger is active
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Monitoring the stream logs in your console
logging:
  level:
    root: INFO
    com.raaz.fraud_detection_system: DEBUG
    org.apache.kafka: WARN
    io.github.resilience4j: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers # Opens the doors to these paths
  endpoint:
    health:
      show-details: always # Vital to see the 'CLOSED/OPEN' status
  health:
    circuitbreakers:
      enabled: true # Specifically links Resilience4j to Actuator

resilience4j:
  circuitbreaker:
    instances:
      kafkaProducer: # This must match the 'name' in your @CircuitBreaker annotation
        registerHealthIndicator: true # This turns 'UNKNOWN' into 'UP'
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.kafka.core.KafkaProducerException
          - java.util.concurrent.ExecutionException
          - java.lang.RuntimeException
          - java.lang.Exception
  ratelimiter:
    instances:
      transactionRateLimiter:
        limitForPeriod: 10 # Only 10 requests...
        limitRefreshPeriod: 1s # ...every 1 second
        timeoutDuration: 0s # Reject immediately if limit is reached