global:
  scrape_interval: 5s # How often to check for new data

scrape_configs:
  - job_name: 'fraud-detection-system'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081'] # Assumes app runs on port 8081